imager/daemon.js
imager/findapng.cpp

Don't throw an exception if file isn't a png.

---

imager/findapng.cpp

As talked in bakape/meguca@49d00f4bd8

Fix magic number compare from findapng.cpp

---

imager/apngDetector.cpp
imager/apngDetector.h
imager/binding.gyp
imager/findapng.cpp

Only C++ implemntation, needs all the JS part to work.
This is the code I used to test it http://pastebin.com/TSsC2xMY.
We should stop reading the file upon getting anything different than 0.
I think javascript is the one who frees the buffer so I didn't do it.
About the implementation: after initializing the object you can call Detect(buffer)
this will return: 0 - If it didn't find anything in the buffer
1 - If the file is an apng
2 - if the file is a normal png and not an apng
It can also throw an exception when the argument given isn't a buffer.

Improve findapng and change it to work with streams

---

client/posts/posting.js

Works without error.
We can make it look pretty later.

Drag and drop functionality added to posting.js

---

client/client.js
client/notify.js
client/posts/models.js

Tab Notifications

---

client/options/background.js

Ocean Blur

---

less/base.less

Fix image hover expansion to respect aspect ratio

---

Makefile
admin/common.js
admin/mnemonic/Makefile
admin/mnemonic/binding.gyp
admin/mnemonic/mnemonics.cpp
admin/mnemonic/mnemonizer.cpp
admin/mnemonic/mnemonizer.h
config/examples/index.js
server/tripcode/tripcode.cc

As talked in the thread.
I realized printf prints to the normal terminal, so I used it to issue warnings, and errors.
I wasn't able to activate mnemonics so the JS part of the implementation might need some testing.
The C++ part was tested here: https://github.com/reiclone/doushio/tree/cmnemonicsTESTS
The results for a 10000 sample test was:
Old:28 ms
New JS:48 ms
New C:19 ms

Change mnemonics algorithm, use c++

---

client/posts/posting.js

Sorry, Just me being retarded again.

Fix Cancel

---

lang/pt_BR/common.js
lang/pt_BR/server.js

I don't know if this will give you problems (because of the bans branch you seem to be working on), so just tell me if that's the case.

Translate remaining strings

---

common/options.js
less/material.less

There are some things I want to add but it is a workable theme at the moment.

Material theme

---

less/inumi.less

i made this css can you put it in plz thx k bye?

Requesting new CSS addition

---

client/posts/render/body.ts
go/src/meguca/util/util.go

add hipster punctuation to punctuation check

---

less/base.less

fixes issue #484 
CSS needed more verbosity for firefox, since chrome assumes some things with display: grid

Fix issue #484

---

client/common/index.ts
client/posts/render/image.ts
go/src/meguca/common/images.go
go/src/meguca/db/images.go
go/src/meguca/db/init.go
go/src/meguca/db/reader.go
go/src/meguca/db/sql/images/write_image.sql
go/src/meguca/db/sql/init/init.sql
go/src/meguca/imager/upload.go
go/src/meguca/templates/article.qtpl
go/src/meguca/templates/index.qtpl
less/base.less

Depends on bakape/thumbnailer/pull/3

Audio/Video Title and Artist Metadata

---

less/base.less

Should solve performance complaints

perf fixes: selector specivity

---

less/inumi.less

fixed the embed look; lightened shadows

Updated inumi.less

---

client/util/scroll.ts

Fixes some bugs with the bottom lock like the thread staying locked in the background, the "locked to bottom" line missing and post links in the url not working on site reloads.

Better bottom lock

---

client/common/index.ts
client/posts/render/body.ts
client_cpp/src/posts/commands.cc
client_cpp/src/posts/models.cc
client_cpp/src/posts/models.hh
docs/json.md
go/src/meguca/common/commands.go
go/src/meguca/common/vars.go
go/src/meguca/db/init.go
go/src/meguca/db/sql/init/init.sql
go/src/meguca/db/sql/posts/decrement_roulette.sql
go/src/meguca/db/sql/posts/reset_roulette.sql
go/src/meguca/db/util.go
go/src/meguca/parser/commands.go
go/src/meguca/templates/body.go
go/src/meguca/templates/body_test.go
less/common.mix.less

Add #roulette command.  The first one has a 1/6 chance of dying, then 1/5, etc.  Once someone dies, it resets to 1/6.  The current state for the command is stored in the db, similar to how #pyu works.

Add #roulette command

---

go/src/meguca/websockets/post_creation.go
go/src/meguca/websockets/post_updates.go

Poster is banned from the board for 30 seconds if they lose at #roulette
Some screenshots below

meme ban posts that lose at #roulette

---

client/common/index.ts
client/posts/render/body.ts
client_cpp/src/posts/commands.cc
client_cpp/src/posts/models.cc
client_cpp/src/posts/models.hh
docs/json.md
go/src/meguca/common/commands.go
go/src/meguca/common/vars.go
go/src/meguca/db/init.go
go/src/meguca/db/sql/init/init.sql
go/src/meguca/db/sql/posts/get_rcount.sql
go/src/meguca/db/sql/posts/increment_rcount.sql
go/src/meguca/db/util.go
go/src/meguca/parser/commands.go
go/src/meguca/templates/body.go
go/src/meguca/templates/body_test.go
go/src/meguca/websockets/post_updates.go

The initial value is computed by checking the mod-log.  After that, the counter is incremented each time someone is banned by #roulette

Add #rcount command, the number of bans from #roulette

---

go/src/meguca/auth/captcha.go

While looking for #665 related issues, fixed this silliness.

Pointless extra multiplication removed

---

.npmignore
index.js
package.json

For easier integration into [linux distribution packages](https://github.com/NixOS/nixpkgs/pull/39482).
Once this is pulled I will update the [npm package](https://www.npmjs.com/package/meguca).

js: npm registry package

---

client/options/index.ts
client/options/specs.ts
client/posts/posting/index.ts
client/ui/keyboard.ts
go/src/meguca/templates/specs.go
lang/en_GB/server.json
lang/es_ES/server.json
lang/fr_FR/server.json
lang/pl_PL/server.json
lang/pt_BR/server.json
lang/ru_RU/server.json
lang/sk_SK/server.json
lang/tr_TR/server.json
lang/uk_UA/server.json
lang/ya_AR/server.json

client: Add post cancel shortcut

---

client/posts/posting/index.ts
client/posts/posting/paste.ts

client: Enable pasting images from clipboard

---

client/posts/embed.ts
go/src/meguca/templates/body.go
go/src/meguca/templates/body_test.go

I've been wanting to get this done for a long time now.
It works just fine, so please tell me there's a better way to get the title than a CORS proxy.

client, templates: Add HookTube provider

---

client/posts/embed.ts
go/src/meguca/templates/body.go
go/src/meguca/templates/body_test.go

Another day, another pull request.

client, templates: Various youtube/hooktube embed fixes

---

package-lock.json
package.json

I forgot to update the package-lock.json.

js: Update package-lock.json and bump version

---

client/posts/embed.ts

client: Genericise duplicate code

---

go/src/meguca/common/commands_test.go
go/src/meguca/common/posts.go
go/src/meguca/db/upkeep.go
go/src/meguca/db/upkeep_test.go
go/src/meguca/parser/body.go
go/src/meguca/parser/body_test.go
go/src/meguca/parser/commands.go
go/src/meguca/parser/commands_test.go
go/src/meguca/templates/body.go

Fixes #741
Also your merge-pyu branch.

db, parser, common: Fix null command

---

go/src/meguca/db/commands.go
go/src/meguca/db/migrations.go
go/src/meguca/db/upkeep.go
go/src/meguca/parser/commands.go
go/src/meguca/parser/commands_test.go

db, parser: Revamp #pyu logic

---

client/frontend/posts/model.ts
client/frontend/posts/render/body.ts
client_cpp/src/posts/body.cc
go/src/meguca/config/config.go
go/src/meguca/templates/body.go
go/src/meguca/templates/body_test.go

client/cpp, config, templates: Change bold formatting from '__' to '@@'

---

package-lock.json
package.json

Gonna have to update the npm package.
If you plan on adding/upgrading/removing any javascript dependencies soon, please say so, so I can add another commit then without having to increment the version.

client: Increment version and update package-lock.json

---

go/src/meguca/server/router.go

Fixes #750
Not really sure how to test this, but unless you see anything obviously wrong, this should work.

router: Implement health check for API

---

client/frontend/posts/embed.ts
go/src/meguca/server/router.go
less/posts.mix.less

client, server: Do not rely on the CORS proxy for HookTube video title

---

client/posts/embed.ts
go/src/meguca/server/router.go

client, server: Fix API HookTube typo

---

go/src/meguca/server/router.go

server: Fix API health check typo

---

go/src/meguca/templates/article.qtpl
go/src/meguca/templates/board.qtpl

templates: Fix small HTML bug

---

package-lock.json
package.json

Updating the meguca nix expression.

JS: Bump version, update package-lock.json

---

go/src/meguca/db/migrations.go
go/src/meguca/db/util.go
go/src/meguca/geoip/db.go
go/src/meguca/server/init.go

Fixes #812
This was a surprising rabbit hole.

server: Download 'GeoLite2-Country.mmdb' if not detected

---

go/src/meguca/db/report.go

db: If reported content is illegal, log error and email

---

client/posts/posting/image.ts
client/posts/posting/index.ts

client: Add capturing event handler for broken images

---

go/src/meguca/server/embed.go

server: Return 415 if YouTube keywords contain live or stream

---

go/src/meguca/common/errors.go

common: Censor ytdl error with less precision

---

client/posts/model.ts
client/posts/view.ts
client/util/time.ts
go/src/meguca/db/admin.go
go/src/meguca/db/bans.go
go/src/meguca/templates/article.go
go/src/meguca/templates/article.qtpl

Fixes #857
Do you see anything else that might be a problem?
I can't exactly test whether or not the ban itself shows up live for others.

 client, templates: Fix ban post status

---

client/posts/inlineExpansion.ts

Fixed some other bugs that didn't show up in my local testing too.

client: Also contract backlinks

---

package-lock.json
package.json

Please bump the meguca version in package.json when [changing](https://github.com/bakape/meguca/commit/091d9188b45b6872bfd34502bb01eed4fcd9ddfd) it.

js: Bump meguca version

---

client/posts/posting/model.ts

client: Fix paste cursor offset

---

go/src/meguca/geoip/db.go

Fixes #914 
I don't really have the mind right now to rewrite the geoip module for this, so here's a temporary fix until I get to it.

 geoip: Use archiver v2 until geoip rewrite 

---

package.json

Related: https://github.com/NixOS/nixpkgs/issues/51616

JS: Bump version

---

client/page/thread_watcher.ts

client: Fix Firefox push notification thumbnail

---

server/src/meguca/server/admin.go

server: Lower required moderation level for unbanning

---

docs/installation.md

This should only be to the local directory.

Don't git clone to root

---

docs/installation.md

Thanks to anon for pointing this out.

Fix the other (root)/meguca mentions

---

client/options/background.ts

client: Fix background video workmode toggle

---

server/src/meguca/parser/commands.go
server/src/meguca/websockets/post_updates.go

You asked for this.
Now all must burn.

parser, websockets: Increase severity of roulette/pyu memebans

---

package-lock.json
package.json

npm: version: 1.1.3 -> 1.1.4

---

static/src/lang/fr_FR/server.json

Update french localization

---

client/options/meguTV.ts

Client: make workmode hide meguTV

---

client/options/nowPlaying.ts
templates/specs.go

Implements https://github.com/bakape/meguca/issues/1019

Fixes #1019 - Add both option for radio bar

---

client/page/thread.ts

Currently goes from 1 day to 0 hours, will now show the correct amount of hours.

Client: fix TTL

---

package-lock.json
package.json

npm: update meguca version

---

client/util/index.ts

client: Fix paste when contents is post ID quote

---

client/posts/posting/drop.ts

ie. dragging and dropping from twitter made the filename "<name>?format=jpg&name=orig.jpg"
tehepelo

oops, forgot about query/fragment part

---

client/options/nowPlaying.ts

fix now playing banner option

---

db/images.go
websockets/feeds/megu_tv.go

meguTV: ignore videos on deleted posts

---

db/images.go

mtv: ignore spoilered videos

---

client/page/thread_watcher.ts

client: last100 thread watcher links

---

docs/installation.md

deps: fix apt package name

---

auth/captcha.go
client/util/index.ts
server/accounts.go
server/accounts_test.go
server/post_creation.go

auth, client, server: fix samesite attribute for cookies

---

README.md
auth/captcha.go
client/util/index.ts
server/accounts.go
server/post_creation.go
util/util.go

Closes #1258
I haven't been able to test it with https, but it should be fine.

cookies: allow unsecure cookies  on localhost

---

client/options/nowPlaying.ts

Forgot the quotes around the title attribute.

client: fix now playing song search tooltip

---

client/options/specs.ts

Seems it's been revived already.

Update Shamiradio URLs

---

server/sse.go

Fucking Cloudflare. It closes the sse connection with a 524 status after 100 seconds of no activity, which should be fixed with this.

sse: stop timeouts closing the connection

---

server/sse.go

It'll definitely work properly this time, absolutely.

sse: fix non-terminating ping message
