- imager/daemon.js
It's always the smallest things.
The following is the output of a wrong dimensioned image.
`` -=>/tmp/magick-75x5siPb PNG 150x150 ``
It was parsing the 75x5 instead of the 150x150.
I made it redo the same thumbnail until it got a wrong dimension, and it went for more than 10k passes  so I'm pretty sure this regex works.
> fix random small thumbnails

- client/hover.js
- client/main.js
- less/base.less
Comparing it to the old client in this one:
- If you preview a post with an expanded image, you see the preview  with a non expanded image.
- Now preview updates as the post is edited.
The first lines of post_preview are copied from the old client, I deducted they force the element to calculate width and height, I don't know if there is a better way.
In the preview you can see links with (you) that you don't see in the normal thread, they are correct so I don't think it's a problem.
I didn't know how to go about what you said of not using the hoverOverlay as an element of the view.
I can make it so it copies the element of the postPreview view, but then I had to make it store a ref to hoverOverlay anyway, and we would have two views with the exact same element so it doesn't feel right …
> Post preview

- client/client.js
- client/posts/models.js
This fixes what you said in the PostPreview PR about links not getting added to the stateLinkerCore if they weren't there at the start of the post.
I didn't find when the post model links where updated, and I found that the old client was updating them here so I just updated them here, if there is a reason you chose not to do this please say so.
Also I don't know if there is a better way to push them into links, one that doesn't force us to manually trigger the event.
> Pass links in post update

- client/options.js
Tested to work on Firefox 38.0 and Chromium 43.0.
Fixes bakape#164.
> Fix option exporting to work on Firefox

- client/posts/posting.js
Should solve #123 .
From what I got it was changing state before insertOwnPost was able to call readable_dice.
I was hesitating about using a sent and seen as indicators, they seemed pretty logical to me, but you may prefer to add another var.
> Wait for insertOwnPost onFinish

- client/client.ts
- client/db.ts
- client/page/common.ts
- client/posts/model.ts
- client/posts/view.ts
- client/state.ts
- client/ui/notification.ts
- client/ui/tab.ts
at some point in the future this could use [IntersectionObserver](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) instead of recomputing on scroll, but that's still too new for now. But recomputation is capped to once every 200ms and skips already-seen posts.
> calculate favicons from post visibility and scrolling

- client/posts/render/body.ts
- go/src/meguca/templates/body.go
- go/src/meguca/templates/body_test.go
- less/common.mix.less
Dice are only formatted if there are at least 2 sides per die, and the maximum possible total was at least 10.  ie \#10d1 would not be formatted, but \#5d2 could be.  The flashing animations go on for about 10 seconds then stop, because CSS animations can cause a lot of CPU usage.
Rolling a 1 makes the roll brown.
Rolling the maximum value makes the roll pink.
Rolling dubs makes the die blue (trips are yellow, quads are green, quints are rainbow).
Rolling a 69 or 6969 makes the roll light pink.
Rolling a 7777 on a d7777 makes the roll rainbow and adds a special message.
> Add flashing colors to dice rolls

- client/posts/render/body.ts
- go/src/meguca/templates/body.go
The kuso_roll class was only being applied to rolls of 1, but it will now be applied to a roll that equals the number of dice rolled.  ie, when each die rolls a 1.
> fix kusorolls for multiple dice

- client/options/loop.ts
- client/posts/view.ts
relative timestamps: read the DOM to check if a mutation is necessary
absolute timestamps: only update the tooltips on mouseover
> Optimize renderTime

- client/posts/view.ts
- client_cpp/src/posts/header.cc
- go/src/meguca/templates/article.go
relative timestamps still only do minutes
> show seconds in absolute timestamps

- Makefile
NixOS has a doCheck option when building packages that does `make check` instead of `make test`.
> make: Added check option for NixOS doCheck

- client/posts/embed.ts
In certain cases, such as `https://www.youtube.com/watch?v=TrgxHDoe8gA&`, can mess up the embed.
> client: Remove '&' option from embed

- go/src/meguca/db/config.go
- go/src/meguca/log/init.go
Here's a slightly saner way to ensure it doesn't email errors or warn of an incorrect email if emailing errors isn't enabled.
I'll submit an issue to upstream and maybe we can disable or change log levels for the email handler under certain conditions.
> log, db: Only enable SMTP if email is enabled

- client/posts/embed.ts
Now we can use `?t=` in embedded Youtube/Hooktube videos.
> client: Enable starting from specified time on embed

- less/tavern.less
It was stretching across a long thread before.
> css: Fix tavern theme

- client/posts/embed.ts
This is a little cleaner, and should take care of a few error cases.
I'm still trying to get in contact with the HookTube devs in the hope that maybe they'll enable CORS on the API server.
> client: Add start and loop parameters, better errors, minor improvements

- go/src/meguca/templates/board.qtpl
Fixes #764
There's a caveat I need your help with, however.
Red/blue text and other formatting shows up fine in the catalog, however red/blue text seems to not work when in the index, or even in the thread OP for that matter. This is only an OP problem, other posts show red/blue fine, both in the thread and index.
Do you know how I can fix this?
> templates: Render formatting in board catalog posts

- go/src/meguca/common/errors.go
- go/src/meguca/server/router.go
> common, server: Ignore invalid YouTube fetch on livestream, use GetVideoInfoFromID

- client/posts/embed.ts
- client/posts/posting/fullscreen.ts
- go/src/meguca/server/embed.go
Fixes #809
Don't merge yet, we need to figure out how we're going to get the actual playing to work.
Unfortunately, it seems that livestreaming isn't standardized yet as far as browsers go, and we'll need for a player for this specific instance.
So far, I'm looking at this: https://github.com/video-dev/hls.js
Now, the problem is, I don't know the best way to work this into meguca's workflow.
If we put it into `package.json` somehow, I think it would go into `www/vendor`, right?
What would you do?
> client, server: Fix YouTube livestream embed

- go/src/meguca/common/errors.go
Fixes #855
This is likely a ytdl issue, so we can just censor the error.
> common: Ignore ytdl signature token parsing error

- client/util/time.ts
- go/src/meguca/templates/article.go
Fixes the incorrect ban times.
It is rounding, so if you do 4 hours and 29 minutes, you will get 4 hours, and 5 hours with 4 hours and 31 minutes. 4 hours and 30 minutes (in the field) will result in 4 hours, because by it is actually 4 hours, 29 minutes and 59 seconds.
> client, templates: Round time properly

- package-lock.json
- package.json
Reasoning:
```
cp node_modules/dom4/build/dom4.js node_modules/core-js/client/core.min.js node_modules/core-js/client/core.min.js.map www/js/vendor
/home/okina/go/src/github.com/bakape/meguca/node_modules/.bin/uglifyjs node_modules/whatwg-fetch/fetch.js -o www/js/vendor/fetch.js
Parse error at node_modules/whatwg-fetch/fetch.js:78,7
export function Headers(headers) {
^
ERROR: Unexpected token: keyword (function)
at JS_Parse_Error.get (eval at <anonymous> (/home/okina/go/src/github.com/bakape/meguca/node_modules/uglify-js/tools/node.js:20:1), <anonymous>:71:23)
at fatal (/home/okina/go/src/github.com/bakape/meguca/node_modules/uglify-js/bin/uglifyjs:291:53)
at run (/home/okina/go/src/github.com/bakape/meguca/node_modules/uglify-js/bin/uglifyjs:235:9)
at Object.<anonymous> …
```
> js: Use version number for whatwg-fetch

- client/posts/posting/model.ts
- client/posts/posting/paste.ts
- client/posts/posting/view.ts
- client/util/index.ts
Fixes #435 
Fixes #600
I chose to not make a newline if the post form is opened by clicking an ID, because you may want to do ">>324532 >>324533 >>324534", etc.
From what I can tell from the testing, this is a nice little QoL improvement.
> client: More usable quoting and pasting

- client/posts/posting/model.ts
Fixes #888
Now, we should be able to do both in a reasonable way.
Test it out and tell me if you like it, please.
Note: If you type something, and then put your cursor to the start of that sentence, and then quote, without any selection, it will do the quote and then a space, instead of newline, this is intentional.
> client: unfuck new quoting

- server/src/meguca/common/errors.go
Fixes #941
If there's another one, I think it may be prudent to just ignore all YouTube errors, at least keep them from sending mail.
> common: Ignore weird YouTube error

- client/options/nowPlaying.ts
now_playing.streamer only updates when a song begins. Use
live.streamer_name instead.
> fix eden banner dj detection

- .gitignore
- Dockerfile
- Makefile
- docs/installation.md
Because downloading a ~90MB file every time you run ``make`` is not ideal.
Full disclaimer, I have not tested the docker change, but it's probably fine.
> deps, docker, make: install extra flags

- client/posts/images.ts
fixes #1082 
Workmode adds an extra child element, which made ``link`` point to the wrong element and override its html.
Also, removing some dead code. The work that it's meant to do is done just above, and since the elements the loop iterates over never have any class, the switch does nothing.
> client: stop element being overwritten

- client/options/specs.ts
Keeps the anchor link in gallery mode so one can mark and jump back to a specific post when leaving gallery mode
> gallery mode: don't hide the post anchor

- client/main.ts
- client/page/thread_watcher.ts
The ``watchThread`` call in ``main.ts`` tried to use the ``watcherPanel`` while it's still null, which would error and stop the page loading.
> client: fix rare load issue

- client/ui/options.ts
`assignValue` incorrectly assumes the value passed is a string for number and range options. This is a problem when the value is zero since assigning an empty string will reset the option to the default.
> Fix default audio volume slider

- client/client.ts
There is no need to explicitly rewrite the URL in the redirect handler because Window.location supports relative URLs.
e.g. location.href = "/a/catalog" will keep the origin hostname.
Also ensure the redirect URL is of an appropriate protocol.
> Remove deploy-specific URLs in redirect handler

- README.md
- auth/captcha.go
- client/options/specs.ts
- client/util/index.ts
- server/accounts.go
- server/accounts_test.go
- server/post_creation.go
- util/util.go
8918ca67f144a017c7d758a53997dc49572b1886 did not revert the localhost-specific logic in the SetCookie helpers. With SameSite Strict or Lax, the Secure attribute is unnecessary and disallows HTTP-only deployment. The host detection is also incorrect. Behind a reverse proxy like nginx, the server will see requests originating from localhost, not the external domain.
> Clean up SameSite cookie changes

- db/bans.go
- db/bans_test.go
- imager/upload.go
- server/util.go
- websockets/post_creation.go
- websockets/synchronisation.go
- websockets/websockets.go
Currently the ban page for global bans only shows when trying to view /all/ even though the poster is banned on all boards.
> moderation: fix ban page for global bans

- client/mod/panel.ts
- client/posts/menu.ts
- server/admin.go
I don't think board creation and deletion count as moderation, so they still need a captcha.
> mod: remove captcha requirement to moderate

- client/options/specs.ts
Apparently they changed the API endpoints again. Also removes the hardcoded station name.
> Update Eden API URL

- db/images.go
- db/upkeep.go
Keep meguTV threads alive indefinitely and also prevents #steal vandalism by shadow bins.
> server: do not delete sticky threads and also prevent #steal on them
